title: <p align="center"> Venugopal Pamidipati </p>
logo: /assets/img/Venu.jpg

description:
  <p align="center">
  <a href="www.linkedin.com/in/venugopalpamidipati">LinkedIn</a> |
  <a href="https://github.com/pamidipati">GitHub</a>
  </p>

theme: jekyll-theme-minimal
